FROM jenkins/jenkins:lts

USER root

# Installa curl e tar
RUN apt-get update && apt-get install -y curl tar

# Crea cartella strumenti
RUN mkdir -p /usr/local/bin/tools

# Scarica kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/tools/

# Scarica Helm
RUN curl -LO https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz \
    && tar -zxvf helm-v3.12.3-linux-amd64.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/tools/ \
    && chmod +x /usr/local/bin/tools/helm \
    && rm -rf linux-amd64 helm-v3.12.3-linux-amd64.tar.gz

# Aggiungi tools al PATH
ENV PATH="/usr/local/bin/tools:${PATH}"

USER jenkins

