- name: Ensure Jenkins agent2 directory exists on new disk
  become: yes
  ansible.builtin.file:
    path: /data/jenkins_agent2
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Remove old Jenkins agent2 container if exists
  become: yes
  ansible.builtin.shell: |
    if [ "$(docker ps -a -q -f name=jenkins-agent2)" ]; then
      docker rm -f jenkins-agent2
    fi
  args:
    executable: /bin/bash

- name: Run Jenkins Agent2 container using Docker CLI
  become: yes
  ansible.builtin.shell: |
    docker run -d \
      --name jenkins-agent2 \
      --network jenkins_net \
      --group-add $(getent group docker | cut -d: -f3) \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /usr/bin/docker:/usr/bin/docker \
      -v /data/jenkins_agent2:/home/jenkins/agent \
      -e JENKINS_URL=http://jenkins-master:8080 \
      -e JENKINS_AGENT_NAME=agent2 \
      -e JENKINS_SECRET=<INSERT_AGENT2_SECRET_HERE> \
      -e JENKINS_WEB_SOCKET=true \
      -e JENKINS_AGENT_WORKDIR=/home/jenkins/agent \
      jenkins/inbound-agent:latest

- name: Wait for Jenkins Agent2 container to start
  become: yes
  retries: 5
  delay: 5
  ansible.builtin.shell: docker inspect -f '{{'{{'}} .State.Running {{'}}'}}' jenkins-agent2
  register: agent_status
  until: agent_status.stdout == "true"
  args:
    executable: /bin/bash

- name: Run Jenkins agent2 JAR inside the container (in background)
  become: yes
  ansible.builtin.shell: |
    docker exec -d jenkins-agent2 bash -c '
      cd /home/jenkins/agent && \
      curl -sO http://jenkins-master:8080/jnlpJars/agent.jar && \
      nohup java -jar agent.jar \
        -url http://jenkins-master:8080/ \
        -secret <INSERT_AGENT2_SECRET_HERE> \
        -name agent2 \
        -webSocket \
        -workDir "/home/jenkins/agent" > agent.log 2>&1 &
    '
  args:
    executable: /bin/bash

